alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: sample-new-nextjs
    match:
      path:
        prefix: /
name: lionfish-app-nextjs1
region: blr
services:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: ksai7991/sample-new-nextjs
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: sample-new-nextjs
  run_command: npm start
  source_dir: /
